baseURL = "https://rmuhamedgaliev.dev/"
languageCode = "en"
defaultContentLanguage = "ru"
title = "Rinat Muhamedgaliev"
preserveTaxonomyNames = true
enableRobotsTXT = true
enableEmoji = true
theme = "paper"
enableGitInfo = false

hasCJKLanguage = false
paginate = 5
googleAnalytics = "UA-157528596-1"

[params]
  github = 'rmuhamedgaliev'

[author]
  name = "Rinat Muhamedgaliev"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Consult"
  weight = 40
  url = "/consult/"

[[menu.main]]
  name = "About"
  weight = 50
  url = "/about/"
